<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="assets\Agent_blue.png" />
    <None Remove="assets\Agent_green.png" />
    <None Remove="assets\Agent_magenta.png" />
    <None Remove="assets\Agent_mint.png" />
    <None Remove="assets\Agent_orange.png" />
    <None Remove="assets\Agent_pink.png" />
    <None Remove="assets\Agent_red.png" />
    <None Remove="assets\Agent_salmon.png" />
    <None Remove="assets\Agent_teal.png" />
    <None Remove="assets\Agent_violet.png" />
    <None Remove="assets\button_l_act_down.png" />
    <None Remove="assets\button_l_act_up.png" />
    <None Remove="assets\button_l_both.png" />
    <None Remove="assets\button_l_down.png" />
    <None Remove="assets\button_l_up.png" />
    <None Remove="assets\button_r_act_down.png" />
    <None Remove="assets\button_r_act_up.png" />
    <None Remove="assets\button_r_both.png" />
    <None Remove="assets\button_r_down.png" />
    <None Remove="assets\button_r_up.png" />
    <None Remove="assets\car.png" />
    <None Remove="assets\car_back.png" />
    <None Remove="assets\car_front.png" />
    <None Remove="assets\car_top.png" />
    <None Remove="assets\door_left.png" />
    <None Remove="assets\door_right.png" />
    <None Remove="assets\door_slider.png" />
    <None Remove="assets\empty.png" />
    <None Remove="assets\floor_back.png" />
    <None Remove="assets\floor_front.png" />
    <None Remove="assets\frame.png" />
    <None Remove="assets\service_back.png" />
    <None Remove="assets\seven_seg_0.png" />
    <None Remove="assets\seven_seg_1.png" />
    <None Remove="assets\seven_seg_2.png" />
    <None Remove="assets\seven_seg_3.png" />
    <None Remove="assets\seven_seg_4.png" />
    <None Remove="assets\seven_seg_5.png" />
    <None Remove="assets\seven_seg_6.png" />
    <None Remove="assets\seven_seg_7.png" />
    <None Remove="assets\seven_seg_8.png" />
    <None Remove="assets\seven_seg_9.png" />
    <None Remove="assets\top_act_down.png" />
    <None Remove="assets\top_act_up.png" />
    <None Remove="assets\wall.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Extended.Wpf.Toolkit" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="assets\Agent_blue.png" />
    <Resource Include="assets\Agent_green.png" />
    <Resource Include="assets\Agent_magenta.png" />
    <Resource Include="assets\Agent_mint.png" />
    <Resource Include="assets\Agent_orange.png" />
    <Resource Include="assets\Agent_pink.png" />
    <Resource Include="assets\Agent_red.png" />
    <Resource Include="assets\Agent_salmon.png" />
    <Resource Include="assets\Agent_teal.png" />
    <Resource Include="assets\Agent_violet.png" />
    <Resource Include="assets\button_l_act_down.png" />
    <Resource Include="assets\button_l_act_up.png" />
    <Resource Include="assets\button_l_both.png" />
    <Resource Include="assets\button_l_down.png" />
    <Resource Include="assets\button_l_up.png" />
    <Resource Include="assets\button_r_act_down.png" />
    <Resource Include="assets\button_r_act_up.png" />
    <Resource Include="assets\button_r_both.png" />
    <Resource Include="assets\button_r_down.png" />
    <Resource Include="assets\button_r_up.png" />
    <Resource Include="assets\car.png" />
    <Resource Include="assets\car_back.png" />
    <Resource Include="assets\car_front.png" />
    <Resource Include="assets\car_top.png" />
    <Resource Include="assets\door_left.png" />
    <Resource Include="assets\door_right.png" />
    <Resource Include="assets\door_slider.png" />
    <Resource Include="assets\empty.png" />
    <Resource Include="assets\floor_back.png" />
    <Resource Include="assets\floor_front.png" />
    <Resource Include="assets\frame.png" />
    <Resource Include="assets\service_back.png" />
    <Resource Include="assets\seven_seg_0.png" />
    <Resource Include="assets\seven_seg_1.png" />
    <Resource Include="assets\seven_seg_2.png" />
    <Resource Include="assets\seven_seg_3.png" />
    <Resource Include="assets\seven_seg_4.png" />
    <Resource Include="assets\seven_seg_5.png" />
    <Resource Include="assets\seven_seg_6.png" />
    <Resource Include="assets\seven_seg_7.png" />
    <Resource Include="assets\seven_seg_8.png" />
    <Resource Include="assets\seven_seg_9.png" />
    <Resource Include="assets\top_act_down.png" />
    <Resource Include="assets\top_act_up.png" />
    <Resource Include="assets\wall.png" />
  </ItemGroup>

</Project>
